# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coordinator',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='placement.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='iscoordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(),
        ),
    ]
