# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20180901_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='min_cgpa',
            field=models.FloatField(),
        ),
    ]
