# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_company_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='min_cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(),
        ),
    ]
