# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_company_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
