# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-01 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20180902_0415'),
        ('placement', '0004_auto_20180902_0423'),
        ('placement', '0004_auto_20180901_2247'),
    ]

    operations = [
    ]
