# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_auto_20180902_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'submitted'), (2, 'onlineTest'), (3, 'interview'), (4, 'selected')], default=1),
        ),
    ]
