# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_merge_20180901_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
