# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-02 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_auto_20180901_2303'),
        ('placement', '0006_auto_20180902_0540'),
    ]

    operations = [
    ]
