# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-02 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import placement.models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_merge_20180902_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(unique=True, upload_to=placement.models.make_resume_path),
        ),
    ]
